# File: .github/workflows/docker-build.yml
#
# name: Build Docker Image
#
# on:
#   push:
#       branches: [ master ]
#   pull_request:
#        branches: [ master ]
#
# jobs:
#   docker-build:
#       runs-on: ubuntu-latest
#
#       steps:
#         - name: Checkout code
#           uses: actions/checkout@v4
#
#         - name: Set up Docker Buildx
#           uses: docker/setup-buildx-action@v3
#
#         - name: Build Docker image
#           run: |
#             docker build -t my-python-app:latest .
